### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by titimoby** [watchy-community/micropython_playground#4]
Thanks for this repository, I now have Watchy with micropython.
I was wondering if there is a specific firmware to choose because when I followed the first link to the [community wiki](https://watchy-community.github.io/wiki/#/micropython/setup) I ended up to download from the [advised link](https://micropython.org/download/esp32/).

Which means I got [v1.19.1 firmware](https://micropython.org/resources/firmware/esp32-20220618-v1.19.1.bin).

I then downloaded the upload folder content and when I boot my Watchy, I have the following error:
```MPY: soft reboot
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "main.py", line 12, in main
  File "src/watchy.py", line 75, in __init__
  File "lib/display.py", line 55, in __init__
MemoryError: memory allocation failed, allocating 5000 bytes
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32
Type "help()" for more information.
>>> ```

Any idea on what I can try?

(but once more, thanks for the work done 💖)

**Comment by kf0mlb** [comment]
I'm running 1.19.1 as well, so it's not a firmware issue. This past weekend I wrote code to put the battery level on screen, but I didn't have my watch to test (sitting at work on my desk), so it looks like my new font file is too large. I will work on trimming the Monocraft font to just the characters I need, and the Symbols font as well. It was all working Friday last week with just time, date, and weather.

**Comment by titimoby** [comment]
thanks a lot, I'll have a look at all existing libraries in the meantime 👍

**Comment by kf0mlb** [comment]
I need to test the code again tomorrow (left it in the office again!) but I found that the font_to_py code had an option to specify which characters to turn into Python instead of using all the characters in the font file. Specifying the limited number of characters used drastically reduced the file sizes.

Next step is to start cross-compiling files into .mpy if memory allocation is still an issue.

**Comment by kf0mlb** [comment]
@titimoby if you pull the latest code, I shrunk the font files and fix the ADC battery code, so now the watchface displays again.

I am working on tracking down an issue with the ADC battery value because it's nothing like the Arduino battery code. For now it will show full battery.

**Comment by titimoby** [comment]
```MPY: soft reboot
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "main.py", line 12, in main
  File "src/watchy.py", line 88, in __init__
  File "src/watchy.py", line 112, in handle_wakeup
  File "lib/pcf8563.py", line 95, in datetime
  File "lib/pcf8563.py", line 88, in year
  File "lib/pcf8563.py", line 51, in __read_byte
OSError: [Errno 19] ENODEV
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32
Type "help()" for more information.```

Let's say the memory error is fixed ;)

I have some time so I'll try step by step, but from scratch, the folder is still not 100% bullet proof.
I hope I will help you find the source of this error 💪

**Comment by titimoby** [comment]
I narrowed main.py to this code and keep the error.

```
from machine import (
    Pin,
    SoftI2C
)
from lib.pcf8563 import PCF8563
from src.constants import (
    RTC_SDA,
    RTC_SCL
)

pin_rtcsda = Pin(RTC_SDA)
pin_rtcscl = Pin(RTC_SCL)
i2c = SoftI2C(sda=pin_rtcsda, scl=pin_rtcscl)
rtc = PCF8563(i2c)
rtc.datetime()
```

**Comment by kf0mlb** [comment]
I wonder if you have a v1 watch, where I am running the v2 watch. I had the [same ENODEV issue](https://github.com/hueyy/watchy_py/issues/1) when I attempted to run `watchy_py` by [hueyy](https://github.com/hueyy/watchy_py). Give his code a run and see if it loads properly for you, if so it means you have a different RTC than I use.

**Comment by titimoby** [comment]
oh, you're right, hue scripts are working.
or at least for what I can say in a few minutes.
So there are versions for watchy and there is no way to know it before ?

**Comment by titimoby** [comment]
Thanks for all the help anyway 💞
